### ISSUE TITLE
Problem with 23.976 fps MOVs

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/zou#845] opened 2024-08-27 13:06 UTC
**Context**

Studio name: Imaginary Pixels
Kitsu version: 0.19.53
Production type: Feature film

**Describe the bug**

When project is set to 23.976 FPS and MOV videos with such frame rate are uploaded, the Kitsu previews are incorrect. It seems that first frame always gets dubbled and last frame gets cut off.

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser: Chrome
 - Version 127.0.6533.119

**Comment by frankrousseau** [comment] 2024-09-04 16:15
Hi @lukas-remis can you provide us with a 23.976 FPS video?

**Comment by lukas-remis** [comment] 2024-09-06 08:12
Hi @frankrousseau 
Here's a file with just frame numbers in each frame: https://ds.imaginary-pixels.com:6661/sharing/N2XRb3egF
It should show 1001 - 1044, but when project is set to 23.976 and I upload this I get: 1001 twice, and preview video ending at 1043

**Comment by frankrousseau** [comment] 2024-09-08 19:08
I was able to reproduce in the player. Can you confirm that it doesn't occur with playlists?

**Comment by lukas-remis** [comment] 2024-09-09 06:03
Yes, you're right. In playlists it's OK

**Comment by frankrousseau** [comment] 2024-09-10 13:16
Thx, it's a Kitsu bug. It will be fixed in next week release. Thank you for reporting.

**Comment by frankrousseau** [comment] 2024-09-16 08:11
It should be fixed. If the problem persists, please open an issue on the Kitsu repository (it seems to be an UI problem).

**Closed by frankrousseau** 2024-09-16 08:11 UTC
Labels: bug

**Comment by lukas-remis** [comment] 2024-09-16 08:26
Nice, thank you!
