### ISSUE TITLE
Attempting to Delete a Project fails when Edits are populated

### ISSUE THREAD

**Issue by PeteDraper** [cgwire/zou#893] opened 2024-08-13 07:08 UTC
Kitsu 0.19.53

Attempting to delete a project / Episode with the Edits section populated generates a 'An error occurred while deleting this episode. There may be existing data currently linked to it. Are you sure this episode has no sequence linked to it?" message.

Deleting the Edit and then re-trying the project deletion solves this.

**Comment by EvanBldy** [comment] 2024-11-29 02:47
Hi @PeteDraper, 
Thanks for the report. 
I have tried and I cannot reproduce it, it seems that it is already fixed. 

I close this issue, if this bug still occurs can you reopenit ?

**Closed by EvanBldy** 2024-11-29 02:47 UTC
Labels: bug
